# Generated by Django 3.1.4 on 2020-12-19 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('votes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'elections_option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('token', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('voted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'elections_voter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('paused', models.BooleanField(default=False)),
                ('votable', models.IntegerField(default=1)),
                ('voters', models.IntegerField(default=0)),
                ('voted', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=None, null=True)),
                ('end_date', models.DateTimeField(default=None, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
